### ISSUE TITLE
error! which version of numpy?

### ISSUE THREAD

**Issue by avBuffer** [jahongir7174/YOLOv8-qat#2]
1>  python main.py --test

2> error log:
[W NNPACK.cpp:53] Could not initialize NNPACK! Reason: Unsupported hardware.
MACs: 4.396G
Parameters: 3.145M
label.len= 25
Traceback (most recent call last):
  File "main.py", line 315, in <module>
    main()
  File "main.py", line 311, in main
    test(args, params)
  File "/home/anaconda3/envs/YOLO/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "main.py", line 202, in test
    dataset = Dataset(filenames, args.input_size, params, False)
  File "/home/work/YOLOv8-qat/utils/dataset.py", line 22, in __init__
    labels = self.load_label(filenames)
  File "/home/work/YOLOv8-qat/utils/dataset.py", line 221, in load_label
    label = numpy.array(label, dtype=numpy.float32)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (25,) + inhomogeneous part.

**Comment by jahongir7174** [comment]
@avBuffer 
Please, follow the readme file to install the required packages
